server:
  port: 8081

spring:
  application:
    name: graphql-facade-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  endpoint:
    health:
      show-details: always

# enable resilience4j defaults (optional tuning)
resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        failureRateThreshold: 50
    instances:
      bookingService:
        baseConfig: default
      hotelService:
        baseConfig: default
      userService:
        baseConfig: default
